apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: zhegao/demo:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
    - protocol: TCP
      port: 5000
  selector:
    app: demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-staging
  name: demo-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  demo-staging
  template:
    metadata:
      labels:
        app: demo-staging
    spec:
      containers:
        - name: demo
          image: zhegao/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-staging
spec:
  ports:
    - protocol: TCP
      port: 5000
  selector:
    app: demo-staging
  type: ClusterIP